### ISSUE TITLE
Generated dense caption of datasets

### ISSUE THREAD

**Issue by tcc-power** [coranholmes/TEVAD#1]
Hi thanks for your great work, I'm so interested in how different text encoders can influence the model, so could you share the generated dense captions of dataset UCF-Crime (if it's possible XD-violence too please) by onedrive?

**Comment by coranholmes** [comment]
Hi, I have added the captions to onedrive (the same url provided in README). But I highly suggest you generate your captions yourself using more advanced zero-shot captioning model (e.g. blip2). I am looking forward to your experimental results. 😊

**Comment by coranholmes** [comment]
Alternatively, you can use the codes here to generate captions yourself. [LINK](https://github.com/coranholmes/SwinBERT)
