### ISSUE TITLE
Best weight files

### ISSUE THREAD

**Issue by riariam** [coranholmes/TEVAD#2]
Hi, Could you please provide the best model weight files? I'm working on your project but can't seem to find this file. Thanks a lot!

**Comment by coranholmes** [comment]
> Hi, Could you please provide the best model weight files? I'm working on your project but can't seem to find this file. Thanks a lot!

Hi, they are under ./ckpt/my_best/

**Comment by riariam** [comment]
Thank you for your response.

I attempted to train and test the model using the data you provided on the UCF dataset, but the results were quite unexpected. When I retrained the model, the best AUC value I achieved was 0.6000, and it occurred at the 890th epoch. However, when I tested using the weights you provided directly, the best AUC value was 0.5866. This represents a significant deviation from the results reported in the paper.

My environment is as follows:
- Python 3.9
- PyTorch 1.13
- Visdom 0.2.4
I conducted the training on a single RTX 4090 with a batch size of 32, using default settings for the rest.

I'm not sure what might be causing this discrepancy in results. Do you have any insights or thoughts on this matter? Thank you very much for your response.
