### ISSUE TITLE
Model Training Results Differ from Paper

### ISSUE THREAD

**Issue by riariam** [coranholmes/TEVAD#3]
Hi, thank you for your great work.

I attempted to train and test the model using the data you provided on the UCF dataset, but the results were quite unexpected. When I retrained the model, the best AUC value I achieved was 0.6000, and it occurred at the 890th epoch. However, when I tested using the weights you provided directly, the best AUC value was 0.5866. This represents a significant deviation from the results reported in the paper.

My environment is as follows:
- Python 3.9
- PyTorch 1.13
- Visdom 0.2.4
I conducted the training on a single RTX 4090 with a batch size of 32, using default settings for the rest.

I'm not sure what might be causing this discrepancy in results. Do you have any insights or thoughts on this matter? Thank you very much for your response.

**Comment by coranholmes** [comment]
> Hi, thank you for your great work.
> 
> I attempted to train and test the model using the data you provided on the UCF dataset, but the results were quite unexpected. When I retrained the model, the best AUC value I achieved was 0.6000, and it occurred at the 890th epoch. However, when I tested using the weights you provided directly, the best AUC value was 0.5866. This represents a significant deviation from the results reported in the paper.
> 
> My environment is as follows:
> 
>     * Python 3.9
> 
>     * PyTorch 1.13
> 
>     * Visdom 0.2.4
>       I conducted the training on a single RTX 4090 with a batch size of 32, using default settings for the rest.
> 
> 
> I'm not sure what might be causing this discrepancy in results. Do you have any insights or thoughts on this matter? Thank you very much for your response.

This is wired. I have checked my experimental results, even the worst performance wouldn't be that bad. Are you using the text/visual embeddings as well as the correct ground truth file gt-ucf.npy I have provided? And are you using the same arguments I list in README?

How do you get the results 0.6000? Is it shown in the output of the codes? Can you provide the full output (including mean, median, min, max)?

In addition, you can try the following:

To use visual features only, which should produce similar results shown in the original RTFM paper (84.03 in their paper and 83.1 in my experimental records):
```
python main.py --dataset ucf --feature-group vis --max-epoch 1000 --extra_loss
```
Alternatively, I suggest you to try the codes on Shanghai dataset to see whether the performance is also bad.

**Comment by riariam** [comment]
Hi! Thank you very much for your prompt response. 
I realize that it was my list file configuration that caused the discrepancies in the results. 
I also have a question for you: when generating caption subtitles, in the dense_caption_mass.py file, what format should the '--dataset_path' parameter be in? Does it refer to the original videos of UCFCrime? If not, could you please clarify what kind of data format should be provided as input?
Thank you very much for your response.

**Comment by coranholmes** [comment]
> Hi! Thank you very much for your prompt response. I realize that it was my list file configuration that caused the discrepancies in the results. I also have a question for you: when generating caption subtitles, in the dense_caption_mass.py file, what format should the '--dataset_path' parameter be in? Does it refer to the original videos of UCFCrime? If not, could you please clarify what kind of data format should be provided as input? Thank you very much for your response.

I suppose this question is related to this [repo](https://github.com/coranholmes/SwinBERT). You can learn more details by reading the original README [file](https://github.com/coranholmes/SwinBERT/blob/main/README_orig.md) in this repo. Yes, --dataset_path refers to the data path to the video files.
