### ISSUE TITLE
Results in Figure 3. 

### ISSUE THREAD

**Issue by MoshiraAbdalla** [coranholmes/TEVAD#4]
Hello,
Can you please tell me how you produced the results shown in your paper in _Figure 3_?
_(Example results from (a) ShanghaiTech (riding a bike), (b) XD-Violence (riot) , and (c) UCF-Crime (vandalism) datasets.)_

**Comment by coranholmes** [comment]
Hi, the visualization codes are a bit messy so I am afraid it's hard for me to share them with you. With other codes (as well as the captions generated) provided in this repo, you should be able to generate similar figures easily.

**Comment by MoshiraTolbah** [comment]
Thanks for the reply, if you can share any similar  resource or any working example it would be great.

**Comment by coranholmes** [comment]
Unfortunately, I have left the organization where I did this research so I can't find the source codes myself. The general steps are: 1) generate the line charts (matplotlib) 2) get the screen shots 3) use Powerpoint to combine the line chart, the screen shot and the captions.
