### ISSUE TITLE
Shanghai Data not downloadable 

### ISSUE THREAD

**Issue by Aniruth1011** [coranholmes/TEVAD#5]
Whenever I try to run main.py , I am not able to download the shanghai dataset.
Reason is it is not available in visdom server.
![image](https://github.com/coranholmes/TEVAD/assets/116301143/4babd3b3-46a8-4b36-a33b-d2b9fb0f61ab)

Could an alternate link be shared please .

**Comment by coranholmes** [comment]
You should download the shanghai dataset via the links provided in README.
Then change the path in those list files under list folder to your own path.

**Comment by Aniruth1011** [comment]
Thank you . noted

**Comment by Aniruth1011** [comment]
Hi , I also noticed that the code separately treats normal and abnormal
frames , but in case of datasets like Shanghai , we have only normal frames
during training .

In that case , normal input , and abnormal input will be the same
Does that mean for shanghai  , and similar one class models , we can avoid
using abnormal frame
