### ISSUE TITLE
1 class model or 2 class model

### ISSUE THREAD

**Issue by Aniruth1011** [coranholmes/TEVAD#6]
Hi , I notices that the code separately treats normal and abnormal frames , but in case of datasets like Shanghai , we have only normal frames during training . 

In that case , normal input , and abnormal input will be the same . 
Does that mean for shanghai , we can avoid using abnormal frame

**Comment by coranholmes** [comment]
I suggest you read my original paper carefully. Both normal and abnormal frames are used which can be seen from the list file.
