### ISSUE TITLE
Results in Figure 4

### ISSUE THREAD

**Issue by Mikael17125** [coranholmes/TEVAD#8]
Hi, Can you please tell me how you produced the results shown in your paper in Figure 4?
(Figure 4. Example results from (a) ShanghaiTech (riding a bike), (c) XD-Violence (shooting), and (b) UCF-Crime (arrest) datasets showing the contribution of each word in the caption to the snippet anomaly score. An image frame of the abnormal event from the snippet is also shown on the right of each caption.)

How do you get the word's score, did you use an attention map?

**Comment by coranholmes** [comment]
> Hi, Can you please tell me how you produced the results shown in your paper in Figure 4? (Figure 4. Example results from (a) ShanghaiTech (riding a bike), (c) XD-Violence (shooting), and (b) UCF-Crime (arrest) datasets showing the contribution of each word in the caption to the snippet anomaly score. An image frame of the abnormal event from the snippet is also shown on the right of each caption.)
> 
> How do you get the word's score, did you use an attention map?

In Page 8 of original paper, it describes how the scores are calculated in Figure 4. "The score above each word in the caption is the differ- ence between the anomaly score by masking this word and the original anomaly score without masking."
