### ISSUE TITLE
Generate .npy for custom dataset

### ISSUE THREAD

**Issue by 213pk** [coranholmes/TEVAD#9]
How do I generate .npy file if I use my own video to train and test the model? Thanks!

**Comment by coranholmes** [comment]
> How do I generate .npy file if I use my own video to train and test the model? Thanks!

You can read README and train your own dataset.

**Comment by 213pk** [comment]
Thank you very much! How do I generate the ground truth .npy file?

**Comment by coranholmes** [comment]
> Thank you very much! How do I generate the ground truth .npy file?

You have to label your own videos (in frame level) and generate the ground truth.

**Comment by 213pk** [comment]
Could you provide an example code to annotate them? Thank you!

**Comment by coranholmes** [comment]
> Could you provide an example code to annotate them? Thank you!

I don't have a code to annotate them as I use existing datasets.
